### ISSUE TITLE
How to train the eventscape dataset

### ISSUE THREAD

**Issue by Kingtorah** [anusha-devulapally/ER-F2D#1]
Your work is great. How do you train the eventscape dataset?

**Comment by anusha-devulapally** [comment]
Hi @Kingtorah,
Thank you for your supportive words. I've updated the repo for the eventscape_dataset. The key differences from MVSEC include the clip_distance and reg_factor arguments. I hope this helps with your training process. If you have any more questions or need further assistance, please feel free to ask.
Thanks.
